DROP TABLE IF EXISTS valores;

CREATE TABLE valores (
    id_medicion INTEGER PRIMARY KEY AUTOINCREMENT,
    valor_sensor TEXT NOT NULL,
    time_stamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
